import { Option } from '../../components/Select/Select';

export const countries: Option[] = [
  { label: 'UAE', value: 'ae' },
  { label: 'Argentina', value: 'ar' },
  { label: 'Austria', value: 'at' },
  { label: 'Australia', value: 'au' },
  { label: 'Belgium', value: 'be' },
  { label: 'Bulgaria', value: 'bg' },
  { label: 'Brazil', value: 'br' },
  { label: 'Canada', value: 'ca' },
  { label: 'Chile', value: 'ch' },
  { label: 'China', value: 'cn' },
  { label: 'Colombia', value: 'co' },
  { label: 'Cuba', value: 'cu' },
  { label: 'Czechia', value: 'cz' },
  { label: 'Germany', value: 'de' },
  { label: 'Egypt', value: 'eg' },
  { label: 'France', value: 'fr' },
  { label: 'Great Britain', value: 'gb' },
  { label: 'Greece', value: 'gr' },
  { label: 'Hong Kong', value: 'hk' },
  { label: 'Hungary', value: 'hu' },
  { label: 'Indonesia', value: 'id' },
  { label: 'Ireland', value: 'ie' },
  { label: 'Israel', value: 'il' },
  { label: 'India', value: 'in' },
  { label: 'Italy', value: 'it' },
  { label: 'Japan', value: 'jp' },
  { label: 'Korea', value: 'kr' },
  { label: 'Lithuania', value: 'lt' },
  { label: 'Latvia', value: 'lv' },
  { label: 'Morocco', value: 'ma' },
  { label: 'Mexico', value: 'mx' },
  { label: 'Malaysia', value: 'my' },
  { label: 'Nigeria', value: 'ng' },
  { label: 'Netherlands', value: 'nl' },
  { label: 'Norway', value: 'no' },
  { label: 'New Zealand', value: 'nz' },
  { label: 'Philippines', value: 'ph' },
  { label: 'Poland', value: 'pl' },
  { label: 'Portugal', value: 'pt' },
  { label: 'Romania', value: 'ro' },
  { label: 'Serbia', value: 'rs' },
  { label: 'Russia', value: 'ru' },
  { label: 'Saudi Arabia', value: 'sa' },
  { label: 'Sweden', value: 'se' },
  { label: 'Singapore', value: 'sg' },
  { label: 'Slovenia', value: 'si' },
  { label: 'Slovakia', value: 'sk' },
  { label: 'Thailand', value: 'th' },
  { label: 'Turkey', value: 'tr' },
  { label: 'Taiwan', value: 'tw' },
  { label: 'Ukraine', value: 'ua' },
  { label: 'United States', value: 'us' },
  { label: 'Venezuela', value: 've' },
  { label: 'Zambia', value: 'za' },
];

export const categories: Option[] = [
  { label: 'Business', value: 'business' },
  { label: 'Entertainment', value: 'entertainment' },
  { label: 'General', value: 'general' },
  { label: 'Health', value: 'health' },
  { label: 'Science', value: 'science' },
  { label: 'Sports', value: 'sports' },
  { label: 'Technology', value: 'technology' },
];

export const sortBy: Option[] = [
  { label: 'Relevancy', value: 'relevancy' },
  { label: 'Popularity', value: 'popularity' },
  { label: 'Published at', value: 'publishedAt' },
];

export const languages = [
  { label: 'Arabic', value: 'ar' },
  { label: 'German', value: 'de' },
  { label: 'English', value: 'en' },
  { label: 'Spanish', value: 'es' },
  { label: 'French', value: 'fr' },
  { label: 'Hebrew', value: 'he' },
  { label: 'Italian', value: 'it' },
  { label: 'Dutch', value: 'nl' },
  { label: 'Norwegian', value: 'no' },
  { label: 'Portuguese', value: 'pt' },
  { label: 'Russian', value: 'ru' },
  { label: 'Swedish', value: 'sv' },
  { label: 'Chinese', value: 'zh' },
];
