export const MAX_ARTICLE_LENGTH_MOBILE = 190;
export const MAX_ARTICLE_LENGTH_DESKTOP = 145;

export const MAX_NUM_PAGE = 10;
export const MAX_AMOUNT_RECENT_SEARCHES = 5;
export const MAX_LOCAL_STORAGE_SEARCHES = 10;
